- name: install docker
  
  hosts: all

  become: yes

  tasks:
    - name: Update Repository cache

      apt:

        update_cache: true

        cache_valid_time: 3600

        force_apt_get: true

    - name: Install required system packages

      apt: name={{ item }} state=latest

      loop: [ 'apt-transport-https','ca-certificates','curl','software-properties-common','python3-pip','python-pip','python3-setuptools']


    - name: Add docker gpg key

      apt_key:

        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add docker apt repo
      become: yes
      ansible.builtin.apt_repository:

       repo: deb https://download.docker.com/linux/ubuntu focal stable

       state: present

       filename: docker

    - name: Install Docker module for python

      pip:
       name: docker


    - name: Update apt and install docker-ce

      apt: update_cache=yes name=docker-ce state=latest

    - name: make sure docker is running
      ansible.builtin.service:
        name: docker
        state: started
